### ISSUE TITLE
Idempotency issue with aci_rest with example

### ISSUE THREAD

**Issue by dagwieers** [datacenter/ansible-role-aci-model#2]
The example playbook identifies an idempotency issue with the **aci_rest** module (in what could ultimately be an issue within the APIC itself).

Rerunning the playbook always indicates the below task has changed the configuration.
```yaml
TASK [datacenter.aci-model : Add interface selector to interface policy profile] *****************************************************************************************************************
changed: [apic1 -> localhost] => (item={u'access_policy_interface_policy_profile_name': u'leaf_997_998', u'access_policy_interface_policy_profile_interface_selector_int_card': 1, u'access_policy_interface_policy_profile_interface_selector_int_to': 22, u'access_policy_interface_policy_profile_interface_selector_policy_group': u'99_router_01', u'access_policy_interface_policy_profile_interface_selector_policy_group_type': u'accbundle', u'access_policy_interface_policy_profile_interface_selector_name': u'Router01', u'access_policy_interface_policy_profile_interface_selector_int_from': 22})
changed: [apic1 -> localhost] => (item={u'access_policy_interface_policy_profile_name': u'leaf_997', u'access_policy_interface_policy_profile_interface_selector_int_card': 1, u'access_policy_interface_policy_profile_interface_selector_int_to': 33, u'access_policy_interface_policy_profile_interface_selector_policy_group': u'99_baremetal_01', u'access_policy_interface_policy_profile_interface_selector_policy_group_type': u'accportgrp', u'access_policy_interface_policy_profile_interface_selector_name': u'Server01', u'access_policy_interface_policy_profile_interface_selector_int_from': 33})
changed: [apic1 -> localhost] => (item={u'access_policy_interface_policy_profile_name': u'leaf_997', u'access_policy_interface_policy_profile_interface_selector_int_card': 1, u'access_policy_interface_policy_profile_interface_selector_int_to': 34, u'access_policy_interface_policy_profile_interface_selector_policy_group': u'99_baremetal_01', u'access_policy_interface_policy_profile_interface_selector_policy_group_type': u'accportgrp', u'access_policy_interface_policy_profile_interface_selector_name': u'Server02', u'access_policy_interface_policy_profile_interface_selector_int_from': 34})
changed: [apic1 -> localhost] => (item={u'access_policy_interface_policy_profile_name': u'leaf_998', u'access_policy_interface_policy_profile_interface_selector_int_card': 1, u'access_policy_interface_policy_profile_interface_selector_int_to': 35, u'access_policy_interface_policy_profile_interface_selector_policy_group': u'99_baremetal_01', u'access_policy_interface_policy_profile_interface_selector_policy_group_type': u'accportgrp', u'access_policy_interface_policy_profile_interface_selector_name': u'Server02', u'access_policy_interface_policy_profile_interface_selector_int_from': 35})
```

The location of the issue: https://github.com/datacenter/ansible-role-aci-model/blob/c9dc0528636be30da41316843d56a9cc7366685d/tasks/main-json.yml#L159-L168

**Comment by dagwieers** [comment]
@joelwking I wanted to give you a heads up, since you were involved in making **aci_rest** idempotent.

**Comment by joelwking** [comment]
Is there an option in your code to output / debug the response back (imdata)  from the APIC for debugging? For example, depending on how the input and URL is coded, you might get multiple status messages back from the APIC. In this example, there are two instances, one for the fvSubnet and one for the fvRsNdPfxPol. Not certain how your logic might search the response, and for debugging you would need to see that.
```xml
<imdata totalCount="1">
    <fvSubnet childAction="deleteNonPresent" ctrl="" descr="UPDATED_for_IPv6_automation_joelking" dn="uni/tn-common/BD-Common/subnet-[fd00:a:255:64::1/64]" extMngdBy="" ip="fd00:a:255:64::1/64" lcOwn="local" modTs="2017-09-25T10:43:30.569-05:00" monPolDn="" name="" nameAlias="" preferred="no" rn="" scope="public" status="created" uid="8342" virtual="no">
        <fvRsNdPfxPol childAction="deleteNonPresent" forceResolve="yes" lcOwn="local" modTs="2017-09-25T10:43:30.569-05:00" monPolDn="" rType="mo" rn="rsNdPfxPol" state="unformed" stateQual="none" status="created" tCl="ndPfxPol" tContextDn="" tDn="" tRn="" tType="name" tnNdPfxPolName="ACI-Demo-RA" uid="8342"/>
    </fvSubnet>
</imdata>
```

**Comment by dagwieers** [comment]
@joelwking The implementation is here: https://github.com/datacenter/aci-ansible/blob/e87db8f15e34ea7dc2e1b30fd445a4c59561bbc9/library/aci_rest.py#L270-L284

It assumes there is no change, and recursively scans the result. If it finds any indication there was a change, it returns True and stops continuing.

And yes, by default the APIC output is returned in the **imdata** keyword. Here is the output from the task that always induces a change.

```yaml
    "imdata": [
        {
            "infraAccPortP": {
                "attributes": {
                    "childAction": "deleteNonPresent",
                    "descr": "",
                    "dn": "uni/infra/accportprof-leaf_998",
                    "lcOwn": "local",
                    "modTs": "2017-09-07T00:07:29.209+02:00",
                    "monPolDn": "uni/fabric/monfab-default",
                    "name": "leaf_998",
                    "ownerKey": "",
                    "ownerTag": "",
                    "rn": "",
                    "status": "modified",
                    "uid": "15374"
                }
            }
        }
    ],
```
